[tool.poetry]
name = "llm-papers-survey"
version = "0.1.0"
description = ""
authors = ["Raymond Guo <raymond@qingnan.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
